import { ensureDatabaseSchema, getDatabase } from "./turso";

export const alertDistricts = ["All districts", "Mae Sot", "Umphang", "Tha Song Yang", "Mae Ramat", "Phop Phra"] as const;
export const alertLanguages = ["en", "my", "th"] as const;
export const alertSeverities = ["watch", "warning", "critical"] as const;

export type AlertDistrict = typeof alertDistricts[number];
export type AlertLanguage = typeof alertLanguages[number];
export type AlertSeverity = typeof alertSeverities[number];

export type WarningAlertRecord = {
  id: string;
  status: "draft" | "published" | "expired";
  severity: AlertSeverity;
  district: AlertDistrict;
  titleEn: string;
  titleMy: string;
  titleTh: string;
  bodyEn: string;
  bodyMy: string;
  bodyTh: string;
  sourceName: string;
  sourceUrl: string | null;
  observedAt: string | null;
  createdAt: string;
  publishedAt: string | null;
  expiresAt: string;
  createdBy: string;
  triggerKey: string | null;
  autoGenerated: boolean;
};

export type AlertSubscriptionRecord = {
  id: string;
  endpoint: string;
  p256dh: string;
  auth: string;
  district: AlertDistrict;
  language: AlertLanguage;
};

type SqlArgument = string | number | null;
type DatabaseRow = Record<string, unknown>;

async function query(sql: string, args: SqlArgument[] = []) {
  await ensureDatabaseSchema();
  const result = await getDatabase().execute({ sql, args });
  return result.rows as unknown as DatabaseRow[];
}

async function execute(sql: string, args: SqlArgument[] = []) {
  await ensureDatabaseSchema();
  return getDatabase().execute({ sql, args });
}

function text(value: unknown) {
  return value == null ? "" : String(value);
}

function nullableText(value: unknown) {
  return value == null ? null : String(value);
}

function mapAlert(row: DatabaseRow): WarningAlertRecord {
  return {
    id: text(row.id),
    status: text(row.status) as WarningAlertRecord["status"],
    severity: text(row.severity) as AlertSeverity,
    district: text(row.district) as AlertDistrict,
    titleEn: text(row.title_en),
    titleMy: text(row.title_my),
    titleTh: text(row.title_th),
    bodyEn: text(row.body_en),
    bodyMy: text(row.body_my),
    bodyTh: text(row.body_th),
    sourceName: text(row.source_name),
    sourceUrl: nullableText(row.source_url),
    observedAt: nullableText(row.observed_at),
    createdAt: text(row.created_at),
    publishedAt: nullableText(row.published_at),
    expiresAt: text(row.expires_at),
    createdBy: text(row.created_by),
    triggerKey: nullableText(row.trigger_key),
    autoGenerated: Boolean(row.auto_generated),
  };
}

export async function listPublishedAlerts(district?: AlertDistrict) {
  const now = new Date().toISOString();
  const rows = district && district !== "All districts"
    ? await query(
      "SELECT * FROM warning_alerts WHERE status = 'published' AND expires_at > ? AND (district = 'All districts' OR district = ?) ORDER BY published_at DESC LIMIT 20",
      [now, district],
    )
    : await query(
      "SELECT * FROM warning_alerts WHERE status = 'published' AND expires_at > ? ORDER BY published_at DESC LIMIT 20",
      [now],
    );
  return rows.map(mapAlert);
}

export async function listAlertsForAdmin() {
  return (await query("SELECT * FROM warning_alerts ORDER BY created_at DESC LIMIT 100")).map(mapAlert);
}

export async function getWarningAlert(id: string) {
  const rows = await query("SELECT * FROM warning_alerts WHERE id = ? LIMIT 1", [id]);
  return rows[0] ? mapAlert(rows[0]) : null;
}

export async function createWarningAlert(alert: WarningAlertRecord) {
  await execute(
    `INSERT INTO warning_alerts (
      id, status, severity, district, title_en, title_my, title_th, body_en, body_my,
      body_th, source_name, source_url, observed_at, created_at, published_at, expires_at,
      created_by, trigger_key, auto_generated
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      alert.id, alert.status, alert.severity, alert.district, alert.titleEn, alert.titleMy,
      alert.titleTh, alert.bodyEn, alert.bodyMy, alert.bodyTh, alert.sourceName,
      alert.sourceUrl, alert.observedAt, alert.createdAt, alert.publishedAt, alert.expiresAt,
      alert.createdBy, alert.triggerKey, alert.autoGenerated ? 1 : 0,
    ],
  );
  return alert;
}

export async function createAutomatedDraft(alert: WarningAlertRecord) {
  const result = await execute(
    `INSERT INTO warning_alerts (
      id, status, severity, district, title_en, title_my, title_th, body_en, body_my,
      body_th, source_name, source_url, observed_at, created_at, published_at, expires_at,
      created_by, trigger_key, auto_generated
    ) VALUES (?, 'draft', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, 1)
    ON CONFLICT (trigger_key) DO NOTHING RETURNING id`,
    [
      alert.id, alert.severity, alert.district, alert.titleEn, alert.titleMy, alert.titleTh,
      alert.bodyEn, alert.bodyMy, alert.bodyTh, alert.sourceName, alert.sourceUrl,
      alert.observedAt, alert.createdAt, alert.expiresAt, alert.createdBy, alert.triggerKey,
    ],
  );
  return result.rows.length > 0;
}

export async function publishWarningAlert(id: string, publishedBy: string) {
  await execute(
    "UPDATE warning_alerts SET status = 'published', published_at = ?, created_by = ? WHERE id = ? AND status = 'draft'",
    [new Date().toISOString(), publishedBy, id],
  );
  return getWarningAlert(id);
}

export async function expireWarningAlert(id: string) {
  await execute("UPDATE warning_alerts SET status = 'expired' WHERE id = ?", [id]);
  return getWarningAlert(id);
}

export async function upsertAlertSubscription(subscription: AlertSubscriptionRecord) {
  const now = new Date().toISOString();
  await execute(
    `INSERT INTO alert_subscriptions (
      id, endpoint, p256dh, auth, district, language, active, consented_at, updated_at, last_error
    ) VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?, NULL)
    ON CONFLICT (endpoint) DO UPDATE SET
      p256dh = excluded.p256dh,
      auth = excluded.auth,
      district = excluded.district,
      language = excluded.language,
      active = 1,
      updated_at = excluded.updated_at,
      last_error = NULL`,
    [subscription.id, subscription.endpoint, subscription.p256dh, subscription.auth, subscription.district, subscription.language, now, now],
  );
}

export async function deactivateAlertSubscription(endpoint: string, error: string | null = null) {
  await execute(
    "UPDATE alert_subscriptions SET active = 0, updated_at = ?, last_error = ? WHERE endpoint = ?",
    [new Date().toISOString(), error, endpoint],
  );
}

export async function listSubscriptionsForAlert(district: AlertDistrict): Promise<AlertSubscriptionRecord[]> {
  const rows = district === "All districts"
    ? await query("SELECT id, endpoint, p256dh, auth, district, language FROM alert_subscriptions WHERE active = 1 LIMIT 5000")
    : await query(
      "SELECT id, endpoint, p256dh, auth, district, language FROM alert_subscriptions WHERE active = 1 AND (district = 'All districts' OR district = ?) LIMIT 5000",
      [district],
    );
  return rows.map((row) => ({
    id: text(row.id),
    endpoint: text(row.endpoint),
    p256dh: text(row.p256dh),
    auth: text(row.auth),
    district: text(row.district) as AlertDistrict,
    language: text(row.language) as AlertLanguage,
  }));
}

export async function recordAlertDelivery(input: { alertId: string; subscriptionId: string; status: "sent" | "failed"; responseCode: number | null; error: string | null }) {
  await execute(
    `INSERT INTO alert_deliveries (
      id, alert_id, subscription_id, status, attempted_at, response_code, error
    ) VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [
      crypto.randomUUID(), input.alertId, input.subscriptionId, input.status,
      new Date().toISOString(), input.responseCode, input.error?.slice(0, 500) ?? null,
    ],
  );
}
