import { createAutomatedDraft, type AlertDistrict, type AlertSeverity, type WarningAlertRecord } from "../../../../db/earlyWarnings";
import { isAlertEvaluator } from "../../../lib/alertAuth";
import { isEmergencyWaterObservation, isFreshWaterObservation } from "../../../lib/waterAlertPolicy";
import { GET as getGovernmentData } from "../../government-data/route";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

type WaterStation = {
  code: string;
  name: string;
  district: string;
  observedAt: string;
  situationLevel: number;
  levelMsl: number;
  bankDistanceM: number;
};

const districtMap: Record<string, AlertDistrict> = {
  "Mae Sot District": "Mae Sot",
  "Umphang District": "Umphang",
  "Tha Song Yang District": "Tha Song Yang",
  "Mae Ramat District": "Mae Ramat",
  "Phop Phra District": "Phop Phra",
};

async function evaluate(request: Request) {
  if (!await isAlertEvaluator(request)) {
    return Response.json({ error: "Evaluator authorization is required." }, { status: 401 });
  }

  const response = await getGovernmentData();
  if (!response.ok) return Response.json({ error: "Government feeds could not be evaluated." }, { status: 503 });
  const data = await response.json() as { water?: { stations?: WaterStation[]; sourceUrl?: string } | null };
  const monitoringStations = (data.water?.stations ?? []).filter(
    (station) => station.situationLevel >= 4 && districtMap[station.district] && isFreshWaterObservation(station.observedAt),
  );
  const emergencyStations = monitoringStations.filter((station) => isEmergencyWaterObservation(station));
  const created: string[] = [];

  for (const station of emergencyStations) {
    const district = districtMap[station.district];
    const severity: AlertSeverity = "critical";
    const observedAt = station.observedAt || new Date().toISOString();
    const triggerKey = `thaiwater:${station.code}:${observedAt}:${station.situationLevel}`;
    const hours = 12 * 60 * 60 * 1000;
    const alert: WarningAlertRecord = {
      id: `AUTO-${station.code.replace(/[^a-z0-9]/gi, "").slice(0, 16)}-${crypto.randomUUID().slice(0, 6).toUpperCase()}`,
      status: "draft",
      severity,
      district,
      titleEn: `Emergency water review: ${station.name}`,
      titleMy: `${severity === "critical" ? "အလွန်မြင့်မားသော" : "မြင့်မားသော"} ရေအဆင့် စစ်ဆေးရန် - ${station.name}`,
      titleTh: `ตรวจสอบระดับน้ำ${severity === "critical" ? "สูงมาก" : "สูง"}: ${station.name}`,
      bodyEn: `ThaiWater situation level ${station.situationLevel}; level ${station.levelMsl.toFixed(2)} m MSL. Staff must confirm the latest agency bulletin before publishing public instructions.`,
      bodyMy: `ThaiWater အခြေအနေအဆင့် ${station.situationLevel}၊ ရေအဆင့် ${station.levelMsl.toFixed(2)} မီတာ MSL ဖြစ်သည်။ အများပြည်သူညွှန်ကြားချက် မထုတ်ပြန်မီ သက်ဆိုင်ရာဌာန၏ နောက်ဆုံးကြေညာချက်ကို ဝန်ထမ်းက အတည်ပြုရမည်။`,
      bodyTh: `ThaiWater รายงานสถานการณ์ระดับ ${station.situationLevel} ระดับน้ำ ${station.levelMsl.toFixed(2)} เมตร รทก. เจ้าหน้าที่ต้องยืนยันประกาศล่าสุดของหน่วยงานก่อนเผยแพร่คำแนะนำต่อสาธารณะ`,
      sourceName: "ThaiWater",
      sourceUrl: data.water?.sourceUrl ?? "https://www.thaiwater.net/",
      observedAt,
      createdAt: new Date().toISOString(),
      publishedAt: null,
      expiresAt: new Date(Date.now() + hours).toISOString(),
      createdBy: "automated government-feed review",
      triggerKey,
      autoGenerated: true,
    };
    if (await createAutomatedDraft(alert)) created.push(alert.id);
  }

  return Response.json({
    evaluatedAt: new Date().toISOString(),
    flaggedStations: monitoringStations.length,
    emergencyStations: emergencyStations.length,
    staleStations: (data.water?.stations ?? []).filter(
      (station) => station.situationLevel >= 4 && districtMap[station.district] && !isFreshWaterObservation(station.observedAt),
    ).length,
    activeFlags: emergencyStations.map((station) => ({
      stationCode: station.code,
      district: districtMap[station.district],
      situationLevel: station.situationLevel,
      observedAt: station.observedAt,
      bankDistanceM: station.bankDistanceM,
    })),
    draftsCreated: created.length,
    draftIds: created,
  });
}

export function GET(request: Request) {
  return evaluate(request);
}

export function POST(request: Request) {
  return evaluate(request);
}
