import {
  alertDistricts,
  alertSeverities,
  createWarningAlert,
  expireWarningAlert,
  listAlertsForAdmin,
  publishWarningAlert,
  type AlertDistrict,
  type AlertSeverity,
  type WarningAlertRecord,
} from "../../../db/earlyWarnings";
import { isAlertAdmin } from "../../lib/alertAuth";
import { deliverWarningAlert } from "../../lib/pushAlerts";

export const dynamic = "force-dynamic";

function text(value: unknown, maximum: number) {
  return typeof value === "string" ? value.trim().slice(0, maximum) : "";
}

function validUrl(value: unknown) {
  const candidate = text(value, 500);
  if (!candidate) return null;
  try {
    const url = new URL(candidate);
    return url.protocol === "https:" || url.protocol === "http:" ? url.toString() : null;
  } catch {
    return null;
  }
}

function unauthorized() {
  return Response.json({ error: "A valid staff access token is required." }, { status: 401 });
}

export async function GET(request: Request) {
  if (!await isAlertAdmin(request)) return unauthorized();
  return Response.json({ alerts: await listAlertsForAdmin() }, { headers: { "Cache-Control": "no-store" } });
}

export async function POST(request: Request) {
  if (!await isAlertAdmin(request)) return unauthorized();
  if (Number(request.headers.get("content-length") ?? 0) > 32_000) return Response.json({ error: "Alert is too large." }, { status: 413 });

  let body: Record<string, unknown>;
  try {
    body = await request.json() as Record<string, unknown>;
  } catch {
    return Response.json({ error: "Invalid alert." }, { status: 400 });
  }

  const district = text(body.district, 40) as AlertDistrict;
  const severity = text(body.severity, 16) as AlertSeverity;
  const expiresAt = text(body.expiresAt, 40);
  const sourceUrl = validUrl(body.sourceUrl);
  const record: WarningAlertRecord = {
    id: `ALT-${new Date().toISOString().slice(0, 10).replace(/-/g, "")}-${crypto.randomUUID().slice(0, 6).toUpperCase()}`,
    status: "draft",
    severity,
    district,
    titleEn: text(body.titleEn, 160),
    titleMy: text(body.titleMy, 220),
    titleTh: text(body.titleTh, 220),
    bodyEn: text(body.bodyEn, 700),
    bodyMy: text(body.bodyMy, 900),
    bodyTh: text(body.bodyTh, 900),
    sourceName: text(body.sourceName, 160),
    sourceUrl,
    observedAt: text(body.observedAt, 40) || null,
    createdAt: new Date().toISOString(),
    publishedAt: null,
    expiresAt,
    createdBy: "authorized staff",
    triggerKey: null,
    autoGenerated: false,
  };

  if (!alertDistricts.includes(district) || !alertSeverities.includes(severity)) {
    return Response.json({ error: "A valid district and severity are required." }, { status: 400 });
  }
  if (![record.titleEn, record.titleMy, record.titleTh, record.bodyEn, record.bodyMy, record.bodyTh, record.sourceName].every(Boolean)) {
    return Response.json({ error: "All three language versions and a source name are required." }, { status: 400 });
  }
  if (!expiresAt || Number.isNaN(Date.parse(expiresAt)) || Date.parse(expiresAt) <= Date.now()) {
    return Response.json({ error: "Expiry must be a future date and time." }, { status: 400 });
  }
  if (text(body.sourceUrl, 500) && sourceUrl == null) {
    return Response.json({ error: "Source link must be a valid web address." }, { status: 400 });
  }

  await createWarningAlert(record);
  if (body.publish === true) {
    const published = await publishWarningAlert(record.id, "authorized staff");
    const delivery = published ? await deliverWarningAlert(published) : null;
    return Response.json({ alert: published, delivery }, { status: 201 });
  }
  return Response.json({ alert: record }, { status: 201 });
}

export async function PATCH(request: Request) {
  if (!await isAlertAdmin(request)) return unauthorized();
  let body: Record<string, unknown>;
  try {
    body = await request.json() as Record<string, unknown>;
  } catch {
    return Response.json({ error: "Invalid request." }, { status: 400 });
  }
  const id = text(body.id, 80);
  const action = text(body.action, 20);
  if (!id) return Response.json({ error: "Alert ID is required." }, { status: 400 });

  if (action === "expire") {
    return Response.json({ alert: await expireWarningAlert(id) });
  }
  if (action !== "publish") return Response.json({ error: "Unsupported action." }, { status: 400 });

  const alert = await publishWarningAlert(id, "authorized staff");
  if (!alert || alert.status !== "published") return Response.json({ error: "Draft alert was not found." }, { status: 404 });
  const delivery = await deliverWarningAlert(alert);
  return Response.json({ alert, delivery });
}
