"use client";

import { ArrowLeft, BellRing, CheckCircle2, ExternalLink, KeyRound, RefreshCw, Send, ShieldAlert, TriangleAlert } from "lucide-react";
import { FormEvent, useState } from "react";

type AlertRecord = {
  id: string;
  status: "draft" | "published" | "expired";
  severity: "watch" | "warning" | "critical";
  district: string;
  titleEn: string;
  titleMy: string;
  titleTh: string;
  bodyEn: string;
  bodyMy: string;
  bodyTh: string;
  sourceName: string;
  sourceUrl: string | null;
  observedAt: string | null;
  createdAt: string;
  publishedAt: string | null;
  expiresAt: string;
  autoGenerated: boolean;
};

function localDateTime(hoursAhead = 6) {
  const date = new Date(Date.now() + hoursAhead * 60 * 60 * 1000);
  const offset = date.getTimezoneOffset() * 60_000;
  return new Date(date.getTime() - offset).toISOString().slice(0, 16);
}

const initialForm = {
  severity: "warning",
  district: "All districts",
  titleEn: "",
  titleMy: "",
  titleTh: "",
  bodyEn: "",
  bodyMy: "",
  bodyTh: "",
  sourceName: "ThaiWater / responsible local authority",
  sourceUrl: "https://www.thaiwater.net/",
  observedAt: localDateTime(0),
  expiresAt: localDateTime(6),
};

export default function AlertsAdminPage() {
  const [token, setToken] = useState("");
  const [alerts, setAlerts] = useState<AlertRecord[]>([]);
  const [form, setForm] = useState(initialForm);
  const [connected, setConnected] = useState(false);
  const [working, setWorking] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const authorization = { Authorization: `Bearer ${token}` };

  async function loadAlerts() {
    setWorking(true);
    setError("");
    setMessage("");
    try {
      const response = await fetch("/api/alerts-admin", { headers: authorization, cache: "no-store" });
      const result = await response.json() as { alerts?: AlertRecord[]; error?: string };
      if (!response.ok) throw new Error(result.error || "Staff access failed.");
      setAlerts(result.alerts ?? []);
      setConnected(true);
    } catch (caught) {
      setConnected(false);
      setError(caught instanceof Error ? caught.message : "Staff access failed.");
    } finally {
      setWorking(false);
    }
  }

  async function submitAlert(event: FormEvent, publish: boolean) {
    event.preventDefault();
    setWorking(true);
    setError("");
    setMessage("");
    try {
      const response = await fetch("/api/alerts-admin", {
        method: "POST",
        headers: { ...authorization, "Content-Type": "application/json" },
        body: JSON.stringify({ ...form, observedAt: new Date(form.observedAt).toISOString(), expiresAt: new Date(form.expiresAt).toISOString(), publish }),
      });
      const result = await response.json() as { error?: string; delivery?: { configured: boolean; recipients: number; sent: number; failed: number } };
      if (!response.ok) throw new Error(result.error || "Alert could not be saved.");
      setMessage(publish ? `Published. ${result.delivery?.sent ?? 0} notification(s) sent to ${result.delivery?.recipients ?? 0} matching subscriber(s).` : "Draft saved for review.");
      setForm({ ...initialForm, observedAt: localDateTime(0), expiresAt: localDateTime(6) });
      await loadAlerts();
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Alert could not be saved.");
    } finally {
      setWorking(false);
    }
  }

  async function updateAlert(id: string, action: "publish" | "expire") {
    setWorking(true);
    setError("");
    setMessage("");
    try {
      const response = await fetch("/api/alerts-admin", {
        method: "PATCH",
        headers: { ...authorization, "Content-Type": "application/json" },
        body: JSON.stringify({ id, action }),
      });
      const result = await response.json() as { error?: string; delivery?: { recipients: number; sent: number; failed: number } };
      if (!response.ok) throw new Error(result.error || "Alert update failed.");
      setMessage(action === "publish" ? `Published. ${result.delivery?.sent ?? 0} of ${result.delivery?.recipients ?? 0} matching notifications sent.` : "Alert expired.");
      await loadAlerts();
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Alert update failed.");
    } finally {
      setWorking(false);
    }
  }

  async function evaluateFeeds() {
    setWorking(true);
    setError("");
    setMessage("");
    try {
      const response = await fetch("/api/alerts/evaluate", { method: "POST", headers: authorization });
      const result = await response.json() as { error?: string; flaggedStations?: number; draftsCreated?: number };
      if (!response.ok) throw new Error(result.error || "Government feeds could not be checked.");
      setMessage(`Government feeds checked: ${result.flaggedStations ?? 0} level 4-5 station(s), ${result.draftsCreated ?? 0} new review draft(s).`);
      await loadAlerts();
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Government feeds could not be checked.");
    } finally {
      setWorking(false);
    }
  }

  return (
    <main className="admin-shell">
      <header className="help-topbar">
        <a className="brand" href="/"><img className="brand-logo" src="/hwf-site-logo.png" alt="Help Without Frontiers" /><span>FLOODWATCH</span></a>
        <a className="help-back-link" href="/"><ArrowLeft size={16} /> Dashboard</a>
        <span className="admin-restricted"><KeyRound size={15} /> Restricted staff desk</span>
      </header>

      <div className="admin-page">
        <section className="admin-intro">
          <div><p className="eyebrow">WESTERN TAK EARLY WARNING</p><h1>Review and publish alerts</h1><p>Government-feed triggers remain drafts until an authorized staff member verifies the source and publishes all three language versions.</p></div>
          <button type="button" onClick={() => void evaluateFeeds()} disabled={!connected || working}><RefreshCw className={working ? "spinning" : ""} size={17} /> Check government feeds</button>
        </section>

        <section className="admin-access" aria-label="Staff access">
          <KeyRound size={18} />
          <label><span>Staff access token</span><input type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Paste the private staff token" autoComplete="off" /></label>
          <button type="button" onClick={() => void loadAlerts()} disabled={!token || working}>{connected ? "Refresh desk" : "Unlock desk"}</button>
        </section>

        {error && <p className="admin-status error" role="alert"><TriangleAlert size={16} /> {error}</p>}
        {message && <p className="admin-status success" role="status"><CheckCircle2 size={16} /> {message}</p>}

        {connected && (
          <div className="admin-workspace">
            <form className="alert-composer" onSubmit={(event) => void submitAlert(event, false)}>
              <div className="admin-section-heading"><div><span className="panel-kicker">NEW PUBLIC MESSAGE</span><h2>Compose warning</h2></div><ShieldAlert size={20} /></div>

              <div className="composer-grid">
                <label><span>Severity</span><select value={form.severity} onChange={(event) => setForm({ ...form, severity: event.target.value })}><option value="watch">Watch</option><option value="warning">Warning</option><option value="critical">Critical</option></select></label>
                <label><span>District</span><select value={form.district} onChange={(event) => setForm({ ...form, district: event.target.value })}><option>All districts</option><option>Mae Sot</option><option>Umphang</option><option>Tha Song Yang</option><option>Mae Ramat</option><option>Phop Phra</option></select></label>
                <label><span>Observed</span><input type="datetime-local" value={form.observedAt} onChange={(event) => setForm({ ...form, observedAt: event.target.value })} required /></label>
                <label><span>Expires</span><input type="datetime-local" value={form.expiresAt} onChange={(event) => setForm({ ...form, expiresAt: event.target.value })} required /></label>
              </div>

              <fieldset className="language-message"><legend>English</legend><label><span>Title</span><input value={form.titleEn} onChange={(event) => setForm({ ...form, titleEn: event.target.value })} maxLength={160} required /></label><label><span>Action message</span><textarea value={form.bodyEn} onChange={(event) => setForm({ ...form, bodyEn: event.target.value })} maxLength={700} rows={3} required /></label></fieldset>
              <fieldset className="language-message"><legend>မြန်မာ</legend><label><span>ခေါင်းစဉ်</span><input value={form.titleMy} onChange={(event) => setForm({ ...form, titleMy: event.target.value })} maxLength={220} required /></label><label><span>ညွှန်ကြားချက်</span><textarea value={form.bodyMy} onChange={(event) => setForm({ ...form, bodyMy: event.target.value })} maxLength={900} rows={3} required /></label></fieldset>
              <fieldset className="language-message"><legend>ไทย</legend><label><span>หัวข้อ</span><input value={form.titleTh} onChange={(event) => setForm({ ...form, titleTh: event.target.value })} maxLength={220} required /></label><label><span>คำแนะนำ</span><textarea value={form.bodyTh} onChange={(event) => setForm({ ...form, bodyTh: event.target.value })} maxLength={900} rows={3} required /></label></fieldset>

              <div className="composer-grid source-fields">
                <label><span>Verified source</span><input value={form.sourceName} onChange={(event) => setForm({ ...form, sourceName: event.target.value })} required /></label>
                <label><span>Source link</span><input type="url" value={form.sourceUrl} onChange={(event) => setForm({ ...form, sourceUrl: event.target.value })} /></label>
              </div>

              <p className="approval-note"><TriangleAlert size={16} /> Confirm the latest responsible-agency bulletin before publishing evacuation, road-closure, or movement instructions.</p>
              <div className="composer-actions"><button type="submit" disabled={working}>Save draft</button><button type="button" className="publish" disabled={working} onClick={(event) => void submitAlert(event as unknown as FormEvent, true)}><Send size={16} /> Publish and notify</button></div>
            </form>

            <section className="alert-review-queue">
              <div className="admin-section-heading"><div><span className="panel-kicker">REVIEW QUEUE</span><h2>Recent alerts</h2></div><span>{alerts.length}</span></div>
              <div className="admin-alert-list">
                {alerts.map((alert) => (
                  <article className={`admin-alert ${alert.severity}`} key={alert.id}>
                    <header><span className={`severity-pill ${alert.severity}`}>{alert.severity}</span><span className={`admin-alert-status ${alert.status}`}>{alert.status}</span></header>
                    <strong>{alert.titleEn}</strong><p>{alert.bodyEn}</p>
                    <small>{alert.district} · expires {new Date(alert.expiresAt).toLocaleString("en-GB")}</small>
                    <div className="admin-alert-source"><span>{alert.autoGenerated ? "Automated review draft" : "Staff-created"}</span>{alert.sourceUrl && <a href={alert.sourceUrl} target="_blank" rel="noreferrer">{alert.sourceName}<ExternalLink size={13} /></a>}</div>
                    {alert.status === "draft" && <div className="admin-alert-actions"><button type="button" onClick={() => void updateAlert(alert.id, "expire")} disabled={working}>Discard</button><button type="button" className="publish" onClick={() => void updateAlert(alert.id, "publish")} disabled={working}><BellRing size={14} /> Publish</button></div>}
                    {alert.status === "published" && <div className="admin-alert-actions"><button type="button" onClick={() => void updateAlert(alert.id, "expire")} disabled={working}>Expire now</button></div>}
                  </article>
                ))}
                {alerts.length === 0 && <p className="empty-state">No alert drafts or published warnings yet.</p>}
              </div>
            </section>
          </div>
        )}
      </div>
    </main>
  );
}
